- name: Apply ARC limit NOW  # noqa no-changed-when
  become: true
  ansible.builtin.shell: |
    echo "{{ base_zfs_arc_max_bytes }}" > /sys/module/zfs/parameters/zfs_arc_max

- name: Restart alloy service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: alloy
    enabled: true
    state: restarted

- name: Restart node_exporter service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: restarted
