- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    create_home: false
    comment: "Prometheus Node Exporter user"

- name: Create node_exporter directory
  ansible.builtin.file:
    path: "/monitoring/node_exporter"
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: "0775"

- name: Check if version file exists
  ansible.builtin.stat:
    path: "/monitoring/node_exporter/version"
  register: base_base_node_exporter_version_file

- name: Create initial version file
  ansible.builtin.file:
    path: "/monitoring/node_exporter/version"
    state: touch
    owner: node_exporter
    group: node_exporter
    mode: "0775"
  when: not base_base_node_exporter_version_file.stat.exists

- name: Read local node_exporter version
  ansible.builtin.slurp:
    src: "/monitoring/node_exporter/version"
  register: base_node_exporter_version_info

- name: Get latest release
  delegate_to: localhost
  run_once: true
  block:
    - name: Fetch latest release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: base_node_exporter_latest_release
      until: base_node_exporter_latest_release.status == 200
      retries: 5

    - name: "Set node_exporter version to {{ base_node_exporter_latest_release.json.tag_name[1:] }}"
      ansible.builtin.set_fact:
        base_node_exporter_version: "{{ base_node_exporter_latest_release.json.tag_name[1:] }}"

- name: Download latest node_exporter binary
  when: base_node_exporter_version != base_node_exporter_version_info['content']
  ansible.builtin.unarchive:
    remote_src: true
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ base_node_exporter_version }}/node_exporter-{{ base_node_exporter_version }}.linux-amd64.tar.gz"  # noqa yaml[line-length]
    dest: "/monitoring/node_exporter/"
    keep_newer: true
    extra_opts:
      - --strip=1
      - --no-anchored
      - node_exporter
  register: base_node_exporter_downloaded
  notify: Restart node_exporter service

- name: Register version in file  # noqa no-handler
  ansible.builtin.copy:
    content: "{{ base_node_exporter_version }}"
    dest: /monitoring/node_exporter/version
    mode: "0775"
  when: base_node_exporter_downloaded.changed

- name: Make the node_exporter binary executable  # noqa no-handler
  ansible.builtin.file:
    path: "/monitoring/node_exporter/node_exporter"
    state: touch
    owner: node_exporter
    group: node_exporter
    mode: "0775"
  when: base_node_exporter_downloaded.changed

- name: Install node_exporter service
  ansible.builtin.copy:
    src: "node_exporter.service"
    dest: "/etc/systemd/system/node_exporter.service"
    mode: "0775"
  notify: Restart node_exporter service
