- name: Run apt update first
  ansible.builtin.apt:
    update_cache: true

- name: Install common packages
  ansible.builtin.apt:
    pkg:
      - molly-guard
      - tmux
      - htop
      - net-tools
      - dnsutils
      - unzip
      - s3cmd

- name: Run apt autoclean to cleanup
  ansible.builtin.apt:
    autoclean: true

- name: Run apt autoremove to cleanup
  ansible.builtin.apt:
    autoremove: true
