- name: Run apt update first
  ansible.builtin.apt:
    update_cache: yes

- name: Install common packages
  ansible.builtin.apt:
    pkg:
    - molly-guard
    - tmux
    - htop
    - net-tools
    - dnsutils

- name: Run apt autoclean to cleanup
  ansible.builtin.apt:
    autoclean: yes

- name: Run apt autoremove to cleanup
  ansible.builtin.apt:
    autoremove: yes
