- name: Install nginx and certbot
  ansible.builtin.apt:
    pkg:
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present

- name: Check if SSL certificate exists
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ grafana_server_url_fqdn }}/fullchain.pem
  register: grafana_cert_file

# https://github.com/certbot/certbot/issues/4090
- name: Request SSL cert if missing  # noqa no-changed-when
  ansible.builtin.command: >
    certbot certonly
    --nginx
    -d {{ grafana_server_url_fqdn }}
    --non-interactive
    --agree-tos
    --email acme@mbraptor.tech
  when: not grafana_cert_file.stat.exists
  notify: Reload nginx service

- name: Install nginx config for grafana
  ansible.builtin.template:
    src: "grafana-vhost.j2"
    dest: "/etc/nginx/sites-available/grafana"
    mode: "0755"
  notify: Reload nginx service

- name: Enable the nginx site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/grafana"
    dest: "/etc/nginx/sites-enabled/grafana"
    state: link
  notify: Reload nginx service
